spring.mongodb.uri=mongodb+srv://surathgayanatha_db_user:EZGeDG4qGHO7JT7P@cluster0.1rlaikr.mongodb.net/smart_campus?retryWrites=true&w=majority&appName=Cluster0
spring.mongodb.database=smart_campus
server.port=8081