# MongoDB
spring.mongodb.uri=
spring.mongodb.database=smart_campus

# Server
server.port=8081

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=
spring.security.oauth2.client.registration.google.client-secret=
spring.security.oauth2.client.registration.google.scope=email,profile

# JWT
jwt.secret=
jwt.expiration=86400000

# CORS
cors.allowed-origins=http://localhost:5173